### ISSUE TITLE
4.9.0 Java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/load/resource/gif/GifDrawable;

### ISSUE THREAD

**Issue by wensefu** [bumptech/glide#3565]
After I upgrade to 4.9.0,I got this error:(occurs on every device and android version)
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/load/resource/gif/GifDrawable;
        at com.bumptech.glide.Glide.<init>(Glide.java:413)
        at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:509)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:268)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)
        at com.bumptech.glide.Glide.get(Glide.java:168)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:689)
        at com.bumptech.glide.Glide.with(Glide.java:716)

while 4.8.0 is ok.

**no Integration libraries**:

<!-- What devices you managed to get the issue to come up on? For example:
**All device/All Android Version**:

```java
Glide.with(view.getContext())
                .load(url)
                .transition(withCrossFade())
                .into(view);
```

**Comment by wensefu** [comment]
**app module:**
implementation("com.github.bumptech.glide:glide:4.9.0") {
        exclude group: "com.android.support"
    }
    annotationProcessor "com.github.bumptech.glide:compiler:4.9.0"
    implementation("com.github.bumptech.glide:recyclerview-integration:4.9.0") {
        // Excludes the support library because it's already included by Glide.
        transitive = false
    }

**lib module:**
api("com.github.bumptech.glide:glide:4.9.0") {
        exclude group: "com.android.support"
    }
    annotationProcessor "com.github.bumptech.glide:compiler:4.9.0"

**Comment by lekonen** [comment]
Has the issue solved finally?  and how to solve?
