### ISSUE TITLE
Including glide in my project triggers NoClassDefFoundError for other files on Pre Lollipop

### ISSUE THREAD

**Issue by vinaywadhwa** [bumptech/glide#635]
Hi, 
* I am using glide in my project. My project has multiple dependencies (local library projects and remote dependencies). 
* Everything works great on Android 5.0 and up. 
* *BUT* When i run the app on Android 4.4 and below, a NoClassDefFoundError starts to pop up on a lot of classes in my project. When i remove glide from the main project, everything starts to work normal again. 

I'm clueless, any hints on what's going on?

**Comment by TWiStErRob** [comment]
#586 and #578 are similar, but those are `NoSuchMethodError`. Do you have an easy way to repro this? Do you use ProGuard? We don't know what's going on yet, but it seems it affects more people. Do you think it's possible that targeting above L can cause incompatibilities? When you say remove do you mean just the dependency is enough to break it or you actually have to use some classes from the dep?

**Comment by TWiStErRob** [comment]
Do you have a flashed OS or stock? What are you test devices? Please try to give us as much info as you can so we may spot patterns.

**Comment by vinaywadhwa** [comment]
First of all, THANKS for responding and trying to help. I really appreciate it. 
* The issues you mention are not related to this issue at all. A striking difference is that the `NoClassDefFoundError` occurs for classes that are not part of glide. It occurs for classes from OTHER modules.
* No easy way to reproduce it. But i'll try to explain everything i can.

* I have Module A - which is the main app module.
* Then i have Modules B,C,D,E,F - these are in-house(created by myself) library projects. B,C,D have their own remote (google play services, et al) and local dependencies (E,F). A has B,C,D as dependencies.
* A also has some jar dependencies ( Jackson json libraries, sqlcipher etc). These jars are local dependencies (the jar files are physically kept in A's libs folder and are used using the 'compile files' directive in A's build.gradle.
* A also has some remote dependencies (including Glide, and other stuff)

Now i run the app with Glide as a dependency in the A's build.gradle
* It works fine on the LG Nexus 5 with Android 5.1.1
* It crashes with `NoClassDefFoundError` s on Nexus 7 2012 (Android 4.4), Samsung Galaxy Tab 3 (4.2), another Asus tablet (will update model no, Android 4.1.2) and a few other non Lollipop, stock OS devices.

Then, i just remove Glide as a dependency in the A's build.gradle, clean, build and run the app.
* It works fine on the Nexus 5 with Android 5.1.1
* It works on the other devices as well. No NoClassDefFoundError anymore.

Other info - 
* All Stock OS's - in all the devices.
* I am also using Glide Transformations (https://github.com/wasabeef/glide-transformations) . But i tried the above process with and without it and i get the same results.
* No Proguard - this happens in a 'debug' build. I specifically removed all release configurations and proguard related things from my gradle file. The issue still persists.


I'll post my build.gradle with a few names masked..


	apply plugin: 'com.android.application'
	
	android {
	    compileSdkVersion 21
	    buildToolsVersion "21.1.2"
	
	    defaultConfig {
	        applicationId "com.my.app"
	        minSdkVersion 14
	        multiDexEnabled = true
	        targetSdkVersion 21
	        compileOptions {
	            sourceCompatibility JavaVersion.VERSION_1_7
	            targetCompatibility JavaVersion.VERSION_1_7
	        }
	        renderscriptTargetApi 23
	        renderscriptSupportModeEnabled true
	
	    }
	    dexOptions {
	        javaMaxHeapSize "4g"
	    }
	    packagingOptions {
	        exclude 'META-INF/LICENSE'
	        exclude 'META-INF/LICENSE.txt'
	        exclude 'META-INF/NOTICE'
	        exclude 'META-INF/NOTICE.txt'
	    }
	
	    
	    buildTypes {
	      
	    }
	
	    lintOptions {
	        checkReleaseBuilds false
	        abortOnError false
	    }
	
	
	    sourceSets { main { java.srcDirs = ['src/main/java'] } }
	
	    testOptions {
	        unitTests.all {
	            jvmArgs '-XX:MaxPermSize=256m'
	        }
	    }
	}
	
	dependencies {
	    compile project(':B')
	    compile project(':C')
	    compile project(':D')
	    compile project(':BB')
	    compile project(':CC')
	    compile project(':DD')
	    compile files('libs/crittercism_v5_0_4_sdkonly.jar')
	    compile files('libs/httpmime-4.0.3.jar')
	    compile files('libs/json_simple-1.1.jar')
	    compile files('libs/FlurryAnalytics-5.3.0.jar')
	    compile 'com.android.support:design:22.2.1'
	    compile 'com.google.android.gms:play-services-ads:7.8.0'
	    compile 'com.android.support:appcompat-v7:22.2.1'
	    compile 'com.android.support:cardview-v7:22.2.1'
	    compile 'com.android.support:recyclerview-v7:22.2.1'
	    compile 'de.hdodenhof:circleimageview:1.3.0'
	//    compile 'com.github.bumptech.glide:glide:3.6.1'
	    compile ('cn.trinea.android.view.autoscrollviewpager:android-auto-scroll-view-pager:1.1.2') {
	        exclude module: 'support-v4'
	    }
	    compile 'me.relex:circleindicator:1.1.5@aar'
	//    compile 'jp.wasabeef:recyclerview-animators:1.2.2'
	    compile 'com.ms-square:expandableTextView:0.1.4'
	    compile 'net.kianoni:fontloader:0.3.0'
	//    compile 'jp.wasabeef:glide-transformations:1.1.0'
	    compile 'jp.co.cyberagent.android.gpuimage:gpuimage-library:1.3.0'
	    testCompile 'junit:junit:4.12'
	}

**Comment by sjudd** [comment]
You're using multidexing? Do you actually generate multiple dex files if you don't include Glide? 

My guess is that you're using the new incremental build system, which only works on ART devices. I think the incremental build happens to mostly work on dalvik devices if you only actually need a single dex file, but will start crashing immediately if you need multiple dex files. 

I'm not totally familiar with Gradle builds target more recent versions of Android, so the specifics I'm less sure about. That said, I'm 99% sure this is a build issue, not a Glide issue. You can probably reproduce it without depending on Glide by including some arbitrary large library (try guava).

**Comment by TWiStErRob** [comment]
Another way to prove this is to include Glide, but remove some other big library you have and probably suddenly it'll work again.

**Comment by vinaywadhwa** [comment]
Wow, that was precisely it. Thanks a ton for your help.
I followed [this](https://developer.android.com/tools/building/multidex.html) and made it work for pre Lollipop devices. 
Glide on!
